//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GiftGalleryResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GiftGalleryResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GiftGallery.Resources.GiftGalleryResources", typeof(GiftGalleryResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The EmaiID field is required..
        /// </summary>
        public static string errEmailField {
            get {
                return ResourceManager.GetString("errEmailField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Feedback field is required..
        /// </summary>
        public static string errFeedbackField {
            get {
                return ResourceManager.GetString("errFeedbackField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Name field is required..
        /// </summary>
        public static string errNameField {
            get {
                return ResourceManager.GetString("errNameField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmailID.
        /// </summary>
        public static string lblEmailID {
            get {
                return ResourceManager.GetString("lblEmailID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback.
        /// </summary>
        public static string lblFeedback {
            get {
                return ResourceManager.GetString("lblFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string lblNameFld {
            get {
                return ResourceManager.GetString("lblNameFld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string lblSubmitBtn {
            get {
                return ResourceManager.GetString("lblSubmitBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2014 Gift Gallery. All rights reserved..
        /// </summary>
        public static string msgCopyright {
            get {
                return ResourceManager.GetString("msgCopyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for providing your feedback. We will get back to you shortly..
        /// </summary>
        public static string msgFBVBReceipt {
            get {
                return ResourceManager.GetString("msgFBVBReceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Gift Gallery.
        /// </summary>
        public static string msgh1 {
            get {
                return ResourceManager.GetString("msgh1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Featured Products.
        /// </summary>
        public static string msgh3 {
            get {
                return ResourceManager.GetString("msgh3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gift Gallery is the store for people who enjoy collecting gifts and for those discriminating shoppers who like to give unique gifts. We ensure the industry standard of customer service and provides best offers to our customers..
        /// </summary>
        public static string msgHome1 {
            get {
                return ResourceManager.GetString("msgHome1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More from Gift Gallery......
        /// </summary>
        public static string msgHome2 {
            get {
                return ResourceManager.GetString("msgHome2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Awesome Range of GARFIELD Products - Mugs, Sippers, Cushions, Clocks, Keychains and more.....
        /// </summary>
        public static string msgHome3 {
            get {
                return ResourceManager.GetString("msgHome3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Range of FUNKY GIFTS Telephones, Players, Desktop Fans, Amazing Gifts, more....
        /// </summary>
        public static string msgHome4 {
            get {
                return ResourceManager.GetString("msgHome4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback.
        /// </summary>
        public static string msgLegend {
            get {
                return ResourceManager.GetString("msgLegend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback Message.
        /// </summary>
        public static string msgRFMsgVBTitle {
            get {
                return ResourceManager.GetString("msgRFMsgVBTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit Feedback.
        /// </summary>
        public static string msgRfVBTitle {
            get {
                return ResourceManager.GetString("msgRfVBTitle", resourceCulture);
            }
        }
    }
}
